### ISSUE TITLE
Is there any metadata for the data file? 

### ISSUE THREAD

**Issue by mohamed-hachaichi** [radoondas/covid-19-slovakia#2]
Is there any medata for the data file. I'm currently looking for Slovakia "codi deaths" at regional level. I don't know if you can help me with this request. 

Many thanks,

**Comment by radoondas** [comment]
Hello @mohamed-hachaichi , unfortunately I do not maintain covid deaths at regional level (yet). 

You should be looking in to the official data source for Slovakia for covid-19 data: https://github.com/Institut-Zdravotnych-Analyz/covid19-data.

As this is a personal project I cannot promise if I ever add deaths on regional level. 
Good luck.

**Comment by mohamed-hachaichi** [comment]
Well, thank you so much for your help @radoondas. 

Good luck, keep it up.
